name: Build Docker
on:
  push:
    branches:
      - dev
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - run: docker --version
      - run: docker run alpine cat /etc/os-release
      - run: docker run alpine echo "Alpine OK"
      - name: Build image
        run: docker build -t mlops-training .