name: Build Docker
on:
  push:
    branches:
      - dev
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: docker --version
      - run: docker run alpine cat /etc/os-release
      - run: docker run alpine echo "Alpine OK"
      - run: docker build -t mlops-training ..